version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "matheuscl"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "matheuscl"
    labels:
      - "dependencies"
      - "github_actions"
  - package-ecosystem: "pip"
    directory: "/flask"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "matheuscl"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
        minimum-release-age: "14 days"
  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "monthly"
      day: "friday"
    assignees:
      - "matheuscl"
    labels:
      - "dependencies"
      - "angular"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
        minimum-release-age: "14 days"
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rxjs"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@ng-bootstrap/ng-bootstrap"
        update-types: ["version-update:semver-major"]
